version: "3.9"
services:
  go-rest-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./src/:/code/
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: alarm  

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: alarm
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
       - '5432:5432'
